name: Actividad-03

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyMath.sln
      working-directory: MyMath

    - name: Build the project
      run: dotnet build MyMath.sln --configuration Release
      working-directory: MyMath

    - name: Run tests and collect code coverage
      run: dotnet test MyMath.sln --configuration Release --collect:"XPlat Code Coverage"
      working-directory: MyMath

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      run: |
        ReportGenerator "-reports:./MyMath/**/coverage.cobertura.xml" "-targetdir:MyMath/coverage-report" -reporttypes:HTML
      working-directory: MyMath

    - name: Publish coverage report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: MyMath/coverage-report
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'
